Handle chunking and set/append outputs
airplanedev/go-sdk pull request #6
Opened 2021-09-30 07:39 UTC by zhan-airplane

2021-09-30 18:08 UTC, colinking requested changes
Let's figure out a smoother way to express paths, but otherwise looks good.

2021-09-30 18:08 UTC, colinking commented on outputs.go
> +		panic(errors.Wrapf(err, "setting output %s", path))
```suggestion
		panic(errors.Wrapf(err, "appending output with path %s", path))
```

2021-09-30 18:08 UTC, colinking commented on outputs.go
> +		panic(errors.Wrap(err, "setting output"))
```suggestion
		panic(errors.Wrap(err, "appending output"))
```

2021-09-30 18:08 UTC, colinking commented on outputs.go
> +func SetOutputWithPath(value interface{}, path string) error {
Hmm, it would be a pain to construct these paths manually. Should we open-source `path` so that we can use it here?

2021-09-30 19:53 UTC, zhan-airplane commented on outputs.go
> +func SetOutputWithPath(value interface{}, path string) error {
Hmm I'm not opposed to open sourcing `path`, but my initial thought is that unless you're doing something around programmatically generating a bunch of different paths, it shouldn't be particularly hard to construct paths manually? And I don't know if there are that many use cases right now for programmatically generating a lot of paths (except for maybe unusual things to do with arrays), so I'm sort-of-leaning towards punting on this until we see how people actually use these paths

2021-09-30 19:55 UTC, zhan-airplane commented on outputs.go
> +	chunkSize := 8192
I've been using chunk size here (and in the other SDKs) to refer to only the user provided log, I'll add a comment

2021-10-01 15:48 UTC, colinking commented on outputs.go
> +func SetOutputWithPath(value interface{}, path string) error {
I'm open to alternatives here! But I'm worried that by accepting a `string`, it'll be easy to footgun yourself by doing something like this:

```go
airplane.SetOutputWithPath(value, "User Name")
```

Which should actually be this:

```go
airplane.SetOutputWithPath(value, `["User Name"]`)
```

One option is we could expose an API like this:

```go
func SetOutput(value interface{}, path ...interface{}) error {}
```

(and hopefully we can lock down `path` with generics when they launch next year!)

Which should help avoid needing to use the `path` API, since you could do something like:

```go
SetOutput(value, "users", 0, "User Name")
```

2021-10-04 07:23 UTC, zhan-airplane commented on outputs.go
> +func SetOutputWithPath(value interface{}, path string) error {
Ah I like this - it's also less awkward than having `WithPath` functions

2021-10-04 14:13 UTC, colinking approved these changes
🔥

2021-10-04 14:13 UTC, colinking commented on outputs.go
> +// Deprecated: Please use SetOutputWithPath or AppendOutputWithPath instead.
```suggestion
// Deprecated: Please use SetOutput or AppendOutput instead.
```

2021-10-04 14:13 UTC, colinking commented on outputs.go
> +// instead.
```suggestion
// Deprecated: Please use MustSetOutput or MustAppendOutput instead.
```

2021-10-04 14:13 UTC, colinking commented on outputs.go
> +// The produced value can be parsed by FromJS and will produce an identical path.
```suggestion
```

2021-10-04 14:13 UTC, colinking commented on outputs.go
> +func toJS(path ...interface{}) string {
Could you port over a few of the tests for `toJS`, too?

And consider moving this into a separate file, maybe `path.go / path_test.go`

2021-10-04 14:13 UTC, colinking commented on outputs.go
> +// Refer to the docs for a description of the JSON path format.
Since users don't need to provide a string JSON path anymore, this comment might be relevant any more. Do you think we could fit a concise description of how to use `path ...interface{}` here?

2021-10-04 16:39 UTC, merged